version: 0.0
os: linux

files:
  - source: frontend
    destination: /home/ubuntu/app/frontend
  - source: backend
    destination: /home/ubuntu/app/backend
  - source: scripts
    destination: /home/ubuntu/scripts

file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/scripts/*.sh
    mode: 755
    owner: ubuntu
    group: ubuntu
    
  - object: /home/ubuntu/app/backend/**
    mode: 755
    owner: ubuntu
    group: ubuntu
    
  - object: /home/ubuntu/app/frontend/dist/angular-15-crud/**
    mode: 755
    owner: www-data
    group: www-data
    
  - object: /home/ubuntu/app/frontend/**  
    mode: 644      
    owner: ubuntu
    group: ubuntu
    except:
      - "/dist/angular-15-crud/**"


hooks:
  BeforeInstall:
    - location: scripts/install_agent.sh
      timeout: 600
      runas: root

  AfterInstall:
    - location: scripts/stop_server.sh
      timeout: 120
      runas: root
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 120
      runas: ubuntu