version: 0.0
os: linux

files:
  # Copy everything from repo root to EC2 app folder
  - source: /
    destination: /home/ubuntu/app

hooks:
  BeforeInstall:
    # Optional: stop old servers if needed
    - location: scripts/stop_server.sh
      timeout: 120
      runas: ubuntu

  AfterInstall:
    # Install dependencies for backend & frontend
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    # Start backend & frontend servers
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu