version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing Angular CLI"
      - npm install -g @angular/cli

  pre_build:
    commands:
      - echo "Installing frontend dependencies"
      - cd frontend
      - npm ci
      - cd ..

  build:
    commands:
      - echo "Building Angular frontend"
      - cd frontend
      - npx ng build --configuration production
      - cd ../backend
      - echo "Installing backend dependencies"
      - npm ci
      - cd ..

  post_build:
    commands:
      - echo "Preparing artifact for pipeline"
      - cd $CODEBUILD_SRC_DIR
      - ls -R
      - zip -r app.zip frontend/dist backend appspec.yml scripts

artifacts:
  files:
    - app.zip
  discard-paths: yes