version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing Angular CLI..."
      - npm install -g @angular/cli

  pre_build:
    commands:
      - echo "Installing frontend dependencies..."
      - cd frontend
      - npm install
      - cd ..

  build:
    commands:
      - echo "Building Angular frontend..."
      - cd frontend
      - npx ng build --configuration production
      - cd ..

      - echo "Installing backend dependencies..."
      - cd backend
      - npm install
      - cd ..

  post_build:
    commands:
      - echo "Preparing deployment artifact..."
      - ls -R
      - zip -r app.zip frontend/dist backend appspec.yml scripts

artifacts:
  files:
    - app.zip
  discard-paths: yes