name: Build and Push to ECR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ECR_REGISTRY: 945219712738.dkr.ecr.us-east-1.amazonaws.com

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ✅ Create short SHA tag
      - name: Set image tag (first 8 digits of commit SHA)
        run: echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

      # ✅ AWS Login
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::945219712738:role/GithubAction
          aws-region: ${{ env.AWS_REGION }}

      # ✅ ECR Login
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 🚀 Frontend Build & Push
      - name: Build & Push Frontend
        run: |
          docker build -t frontend ./frontend

          # Tag with SHA
          docker tag frontend:latest $ECR_REGISTRY/frontend:$IMAGE_TAG
          docker push $ECR_REGISTRY/frontend:$IMAGE_TAG

          # Tag with latest
          docker tag frontend:latest $ECR_REGISTRY/frontend:latest
          docker push $ECR_REGISTRY/frontend:latest

      # 🚀 Backend Build & Push
      - name: Build & Push Backend
        run: |
          docker build -t backend ./backend

          # Tag with SHA
          docker tag backend:latest $ECR_REGISTRY/backend:$IMAGE_TAG
          docker push $ECR_REGISTRY/backend:$IMAGE_TAG

          # Tag with latest
          docker tag backend:latest $ECR_REGISTRY/backend:latest
          docker push $ECR_REGISTRY/backend:latest

     
