name: Build, Scan, and Push Docker Images

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ECR_REGISTRY: 945219712738.dkr.ecr.us-east-1.amazonaws.com
      ECR_REPOSITORY: frontend
      ECR_REPOSITORY1: backend


    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::945219712738:role/GithubAction
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      # Frontend
      - name: Build Frontend Image
        run: docker build -t frontend ./frontend

      - name: Scan Frontend Image with Trivy
        run: trivy image frontend:latest

      - name: Push Frontend Image to ECR
        run: |
          docker tag frontend:latest $ECR_REGISTRY/$ECR_REPOSITORY:frontend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:frontend

      # Backend
      - name: Build Backend Image
        run: docker build -t backend ./backend

      - name: Scan Backend Image with Trivy
        run: trivy image backend:latest

      - name: Push Backend Image to ECR
        run: |
          docker tag backend:latest $ECR_REGISTRY/$ECR_REPOSITORY1:backend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY1:backend