name: Build and Push Docker Images

on:
  push:
    branches: [ main, Docker ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ECR_REGISTRY: 945219712738.dkr.ecr.us-east-1.amazonaws.com
      ECR_REPOSITORY: my-app1

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::945219712738:role/GithubAction
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create ECR Repository if not exists
        run: |
          aws ecr describe-repositories --repository-names $ECR_REPOSITORY || \
          aws ecr create-repository --repository-name $ECR_REPOSITORY

      - name: Build and Push Frontend Image
        run: |
          docker build -t frontend ./frontend
          docker tag frontend:latest $ECR_REGISTRY/$ECR_REPOSITORY:frontend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:frontend

      - name: Build and Push Backend Image
        run: |
          docker build -t backend ./backend
          docker tag backend:latest 945219712738.dkr.ecr.us-east-1.amazonaws.com/my-app:backend
          docker push 945219712738.dkr.ecr.us-east-1.amazonaws.com/my-app1:backend
          docker tag backend:latest $ECR_REGISTRY/$ECR_REPOSITORY:backend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:backend

