name: Manual Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      frontend_tag:
        description: "Frontend image tag (example: frontend-d8da3df0)"
        required: true
      backend_tag:
        description: "Backend image tag (example: backend-d8da3df0)"
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: us-east-1
      ECR_REGISTRY: 641628981128.dkr.ecr.us-east-1.amazonaws.com
      ECR_REPOSITORY: myapp1_frontend
      ECR_REPOSITORY1: myapp1_backend

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::641628981128:role/github-action
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup SSH (Bastion + EC2)
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.BASTION_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          cat >> ~/.ssh/config <<EOF
          Host bastion
              HostName ${{ secrets.BASTION_HOST }}
              User ${{ secrets.BASTION_USER }}
              IdentityFile ~/.ssh/deploy_key
              StrictHostKeyChecking no

          Host private-ec2
              HostName ${{ secrets.PRIVATE_EC2_HOST }}
              User ${{ secrets.PRIVATE_EC2_USER }}
              IdentityFile ~/.ssh/deploy_key
              ProxyJump bastion
              StrictHostKeyChecking no
          EOF

          chmod 600 ~/.ssh/config

      - name: Rollback application
        run: |
          ssh private-ec2 'bash -s' << EOF
            set -e

            FRONTEND_TAG="${{ github.event.inputs.frontend_tag }}"
            BACKEND_TAG="${{ github.event.inputs.backend_tag }}"

            echo "🔐 Login to ECR..."
            aws ecr get-login-password --region $AWS_REGION | docker login \
              --username AWS \
              --password-stdin $ECR_REGISTRY

            echo "⏪ Rolling back frontend: $FRONTEND_TAG"
            docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$FRONTEND_TAG

            docker service update \
              --image $ECR_REGISTRY/$ECR_REPOSITORY:$FRONTEND_TAG \
              myapp_frontend

            echo "⏪ Rolling back backend: $BACKEND_TAG"
            docker pull $ECR_REGISTRY/$ECR_REPOSITORY1:$BACKEND_TAG

            docker service update \
              --image $ECR_REGISTRY/$ECR_REPOSITORY1:$BACKEND_TAG \
              myapp_backend

            echo "📦 Services after rollback"
            docker stack services myapp
            docker stack ps myapp --no-trunc
          EOF

      - name: Verify rollback
        run: |
          ssh private-ec2 'bash -s' << EOF
            sleep 20

            docker service ls
          EOF
